spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_seller?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: false
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true

server:
  port: 8082
  servlet:
    context-path: /seller

rpc.manager.url: http://localhost:8081/manager/

rpc:
  client:
    url: http://localhost:8081/manager/
    basePackage: com.chen.api

swagger:
  basePackage: com.chen.seller.controller
