server:
  port: 8082
  servlet:
    context-path: /seller

rpc.manager.url: http://localhost:8081/manager/

rpc:
  client:
    url: http://localhost:8081/manager/
    basePackage: com.chen.api

logging:
  level:
    com.googlecode.jsonrpc4j: debug
