spring:
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true

server:
  port: 8082
  servlet:
    context-path: /seller

rpc.manager.url: http://localhost:8081/manager/

rpc:
  client:
    url: http://localhost:8081/manager/
    basePackage: com.chen.api

#logging:
#  level:
#    com.googlecode.jsonrpc4j: debug

