spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/db_financial?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    open-in-view: false
server:
  port: 8080
  servlet:
    context-path: /manager
