spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_manager?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: false
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true

server:
  port: 8081
  servlet:
    context-path: /manager

swagger:
  groupName: manager
  basePackage: com.chen.manager.controller
