spring:
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/db_financial?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    open-in-view: false
  jackson:
    #    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8

server:
  port: 8081
  servlet:
    context-path: /manager

swagger:
  groupName: manager
  basePackage: com.chen.manager.controller

logging:
  level:
    com.googlecode.jsonrpc4j: debug
